# Generated by Django 6.0.6 on 2026-06-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folder_path', models.TextField(unique=True)),
                ('icon', models.CharField(default='folder', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Appareil inconnu', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.TextField(unique=True)),
                ('thumbnail_path', models.TextField(blank=True, null=True)),
                ('duration_sec', models.IntegerField(default=0)),
                ('file_size_mb', models.IntegerField(default=0)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_mb', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='videos.device')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='videos.video')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_sec', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='videos.device')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='videos.video')),
            ],
            options={
                'ordering': ['-watched_at'],
                'unique_together': {('video', 'device')},
            },
        ),
    ]
