# Generated by Django 6.0.6 on 2026-06-25 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Appareil inconnu", max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Appareil",
                "verbose_name_plural": "Appareils",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("folder_path", models.TextField(unique=True)),
                ("icon", models.CharField(default="folder", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catégorie parente si ceci est une sous-catégorie générée depuis un sous-dossier.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="videos.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.TextField(unique=True)),
                ("thumbnail_path", models.TextField(blank=True, null=True)),
                ("duration_sec", models.IntegerField(default=0)),
                ("file_size_mb", models.IntegerField(default=0)),
                ("format", models.CharField(blank=True, max_length=10)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("last_watched", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="videos.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vidéo",
                "verbose_name_plural": "Vidéos",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size_mb", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En cours"),
                            ("done", "Terminé"),
                            ("error", "Erreur"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to="videos.device",
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envoi",
                "verbose_name_plural": "Envois",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("progress_sec", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("watched_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="videos.device",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique",
                "verbose_name_plural": "Historiques",
                "ordering": ["-watched_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_category_name_per_parent"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watchhistory",
            unique_together={("video", "device")},
        ),
    ]
