# Generated by Django 6.0.6 on 2026-06-16 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_device_name_alter_upload_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-last_seen'], 'verbose_name': 'Appareil', 'verbose_name_plural': 'Appareils'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Envoi', 'verbose_name_plural': 'Envois'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Vidéo', 'verbose_name_plural': 'Vidéos'},
        ),
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-watched_at'], 'verbose_name': 'Historique', 'verbose_name_plural': 'Historiques'},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='Appareil inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
