# Generated by Django 6.0.6 on 2026-06-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_category_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload', to='videos.video'),
        ),
    ]
