# Generated by Django 6.0.6 on 2026-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_upload_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
